export const ADD_HEADER_ITEM = 'ADD_HEADER_ITEM';

export const ADD_NEW_POST = 'ADD_NEW_POST';

export const FETCH_MAIN_CONTENT_START = 'FETCH_MAIN_CONTENT_START';
export const FETCH_MAIN_CONTENT_SUCCESS = 'FETCH_MAIN_CONTENT_SUCCESS';
export const FETCH_MAIN_CONTENT_FAIL = 'FETCH_MAIN_CONTENT_FAIL';