export const ADD_HEADER_ITEM = 'ADD_HEADER_ITEM';

export const ADD_NEW_POST_START = 'ADD_NEW_POST_START';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';
export const ADD_ANIMATE_SCS_ERR_BTN = 'ADD_ANIMATE_SCS_ERR_BTN';
export const ADD_NEW_POST_CONTAINER = 'ADD_NEW_POST_CONTAINER';

export const ADD_NEW_NEWS_MEDIA_CONTAINER_START = 'ADD_NEW_NEWS_MEDIA_CONTAINER_START';
export const ADD_NEW_NEWS_MEDIA_CONTAINER_SUCCESS = 'ADD_NEW_NEWS_MEDIA_CONTAINER_SUCCESS';
export const ADD_NEW_NEWS_MEDIA_CONTAINER_FAIL = 'ADD_NEW_NEWS_MEDIA_CONTAINER_FAIL';
export const ADD_NEW_NEWS_MEDIA_CONTAINER = 'ADD_NEW_NEWS_MEDIA_CONTAINER';

export const UPDATE_POST_DATA = 'UPDATE_POST_DATA';

export const FETCH_MAIN_CONTENT_START = 'FETCH_MAIN_CONTENT_START';
export const FETCH_MAIN_CONTENT_SUCCESS = 'FETCH_MAIN_CONTENT_SUCCESS';
export const FETCH_MAIN_CONTENT_FAIL = 'FETCH_MAIN_CONTENT_FAIL';

export const FETCH_NEWS_MEDIA_SUCCESS = 'FETCH_NEWS_MEDIA_SUCCESS';

export const FETCH_TEXT_SUCCESS = 'FETCH_TEXT_SUCCESS';

export const FETCH_POST_CONTENT_START = 'FETCH_POST_CONTENT_START';
export const FETCH_POST_CONTENT_SUCCESS = 'FETCH_POST_CONTENT_SUCCESS';
export const FETCH_POST_CONTENT_FAIL = 'FETCH_POST_CONTENT_FAIL';
export const FETCH_POST_URL_LIST = 'FETCH_POST_URL_LIST';



export const CREATE_MAIN_CONTENT_VARIABLE = 'CREATE_MAIN_CONTENT_VARIABLE';