export const ADD_HEADER_ITEM = 'ADD_HEADER_ITEM';

export const ADD_NEW_POST_START = 'ADD_NEW_POST_START';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';

export const FETCH_MAIN_CONTENT_START = 'FETCH_MAIN_CONTENT_START';
export const FETCH_MAIN_CONTENT_SUCCESS = 'FETCH_MAIN_CONTENT_SUCCESS';
export const FETCH_MAIN_CONTENT_FAIL = 'FETCH_MAIN_CONTENT_FAIL';
